# Generated by Django 3.1.7 on 2021-08-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regi',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='regi',
            name='name',
        ),
        migrations.AddField(
            model_name='regi',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='regi',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='regi',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
