# Generated by Django 3.1.7 on 2021-08-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0002_auto_20210802_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='regi',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
